# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            nsgrantham
tagline:          Neal Grantham
description:      Neal Grantham
permalink:        /:title/

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  false

disqus:
  shortname:      'nsgrantham-blog'

google_analytics: UA-53171020-1